version: "3.7"
services:
    survey-frontend:
      container_name: survey-frontend-container
      image: mulukenh/surveyfrontend:latest
      build: 
        context: .
        dockerfile: surveyfrontend.dockerfile
      depends_on: 
        - survey-tomcat
      ports:
        - 8200:80
      networks:
        - survey-app-network
  
    survey-maven:
      container_name: survey-maven
      image: mulukenh/surveymaven:latest
      volumes:
        - source_data:/app/target
      build: 
        context: .
        dockerfile: surveymaven.dockerfile
      environment:
        - DB_CONNECTION_URL=${DB_CONNECTION_URL}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD} 
        
    survey-tomcat:
      container_name: survey-tomcat
      image: mulukenh/surveytomcat:latest
      volumes:
        - source_data:/usr/local/tomcat/webapps
      build: 
        context: .
        dockerfile: surveytomcat.dockerfile
      ports:
        - "8080:8080"
      links:
        - survey-db
      networks:
        - survey-app-network 
      depends_on:
        - survey-maven
      environment:
        - DB_CONNECTION_URL=${DB_CONNECTION_URL}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD} 

    survey-db:
      container_name: surveydb-container
      image: mulukenh/surveydb:latest
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      build:
        context: .
        dockerfile: surveydb.dockerfile
      environment:
        - MYSQL_HOST=${DB_HOST}
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_ROOT_USERNAME=${DB_USER}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}  
      ports:
        - 3306:3306
      networks:
        - survey-app-network
      cap_add:
        - SYS_NICE 

volumes:
  db_data:
  source_data:

networks:
  survey-app-network:
    driver: bridge




