version: "3.7"
services:
    survey-frontend:
      container_name: survey-frontend-container
      image: mulukenh/surveyfrontend:latest
      build: 
        context: .
        dockerfile: surveyfrontend.dockerfile
      depends_on: 
        - survey-backend
      ports:
        - 8200:80
      networks:
        - survey-app-network
        
    survey-backend:
      container_name: survey-backend-container
      image: mulukenh/surveybackend:latest
      build: 
        context: .
        dockerfile: surveybackend.dockerfile
      ports:
      - "8080:8080"
      # depends_on:
      #   - survey-db
      networks:
        - survey-app-network

    # survey-db:
    #   container_name: surveydb-container
    #   image: mulukenh/surveydb:latest
    #   restart: always
    #   build:
    #     context: .
    #     dockerfile: surveydb.dockerfile
    #   ports:
    #     - "3306:3306"
    #   expose:
    #     - "3306"
    #   volumes:
    #     - db_data:/var/lib/mysql
    #   environment:
    #     MYSQL_ROOT_HOST: localhost
    #     MYSQL_DATABASE: surveydb
    #     MYSQL_ROOT_USER: surveydbadmin
    #     MYSQL_ROOT_PASSWORD: password
    #   networks:
    #     - survey-app-network
# volumes:
#     db_data:
  
networks:
    survey-app-network:
      driver: bridge




